# Generated by Django 3.1.3 on 2020-11-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201128_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'أنثى'), ('FEMALE', 'ذكر'), ('SHEMALE', 'خول')], max_length=50, verbose_name='الجنس'),
        ),
    ]
