# Generated by Django 3.1.3 on 2020-11-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201129_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=225, verbose_name='العنوان التفصيلى'),
        ),
    ]
