# Generated by Django 3.1.3 on 2020-11-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201129_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=None, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
    ]
