# Generated by Django 3.1.3 on 2020-11-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
