# Generated by Django 3.1.3 on 2020-11-29 11:35

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الخدمة')),
                ('image', stdimage.models.StdImageField(upload_to='service_images', verbose_name='صورة الخدمة')),
            ],
        ),
    ]
