# Generated by Django 3.1.3 on 2020-11-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image2',
            field=models.ImageField(default=None, height_field=200, upload_to='service_images', verbose_name='', width_field=300),
            preserve_default=False,
        ),
    ]
