# Generated by Django 3.1.3 on 2021-04-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeworkimages',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='EmployeeWOrkImages',
        ),
    ]
