# Generated by Django 3.1.3 on 2020-12-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.CharField(default=1, max_length=50, verbose_name='معلومات الموظف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default=None, upload_to='', verbose_name='صورة الموظف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
