# Generated by Django 3.1.3 on 2020-12-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20201202_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='about',
            field=models.CharField(max_length=225, verbose_name='معلومات الموظف'),
        ),
    ]
