# Generated by Django 3.1.3 on 2020-12-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20201202_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='اسم القطعة')),
                ('price', models.IntegerField(verbose_name='السعر')),
                ('details', models.CharField(max_length=225, verbose_name='التفاصيل')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part', to='service.service', verbose_name='الخدمة')),
            ],
        ),
    ]
