# Generated by Django 3.1.3 on 2020-12-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_spareparts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spareparts',
            options={'verbose_name': 'قطعة الغيار', 'verbose_name_plural': 'قطع الغيار'},
        ),
        migrations.AddField(
            model_name='spareparts',
            name='photo',
            field=models.ImageField(default=None, upload_to='', verbose_name='صورة المنتج'),
            preserve_default=False,
        ),
    ]
