# Generated by Django 3.1.3 on 2020-12-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20201205_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر'),
        ),
    ]
