# Generated by Django 3.1.3 on 2020-12-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20201205_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='السعر'),
        ),
    ]
