# Generated by Django 3.1.3 on 2020-12-07 21:28

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20201205_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rate',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, max_length=2, verbose_name='تقييم الموظف من 5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EGP', max_digits=14, verbose_name='سعر القطعة'),
        ),
    ]
