# Generated by Django 3.1.3 on 2020-12-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20201207_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.TimeField(auto_now=True, verbose_name='وقت الطلب'),
        ),
    ]
