# Generated by Django 3.1.3 on 2020-12-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20201207_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='author',
        ),
        migrations.RemoveField(
            model_name='request',
            name='updated_by',
        ),
    ]
