# Generated by Django 3.1.3 on 2020-12-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_request_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-id'], 'verbose_name': 'الطلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AddField(
            model_name='request',
            name='done',
            field=models.BooleanField(default=False, verbose_name='تم تنفيذ الخدمة'),
        ),
    ]
