# Generated by Django 3.1.3 on 2021-03-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_request_show_in_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='employee_images', verbose_name='صورة الموظف'),
        ),
    ]
