# Generated by Django 3.1.3 on 2021-03-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_auto_20210319_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='photo',
            field=models.ImageField(upload_to='SpareParts_images', verbose_name='صورة المنتج'),
        ),
    ]
