# Generated by Django 3.1.3 on 2021-03-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWOrkImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='employee_work_images', verbose_name='صورة العمل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.employee', verbose_name='العامل')),
            ],
        ),
    ]
