# Generated by Django 3.1.3 on 2021-03-23 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_auto_20210323_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkimages',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_image', to='service.employee', verbose_name='العامل'),
        ),
    ]
