# Generated by Django 3.1.3 on 2021-03-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_auto_20210323_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeworkimages',
            old_name='image',
            new_name='images',
        ),
    ]
